[[checklist]]
Checklist
---------

As a technopolitical project, Decidim needs several things to work. This
is a non comprehensive list that serves as a general recommendation of
what things you need to have it working with the best practices:

[[technological]]
Technological
~~~~~~~~~~~~~

1.  Choose a *domain* for your application. Some typical names involve
"Participation" or "Decision" conjugations.
2.  Choose which *languages* do you want for your application. In case
that your language isn't supported you should translate it on
https://crowdin.com/project/decidim[Crowdin].
3.  Customize the link:customization/styles.md[*look and feel*] (colors,
pictures, fonts, etc).
4.  Configure *SSL*. We recommend using at least
https://letsencrypt.org/[Let's Encrypt] for a minimum security. You
should also check that there's an enforced redirection from HTTP to
HTTPS on your web server.
5.  Configure your *SMTP* server.
6.  Setup the *geolocation* service. We recommend using
https://developer.here.com/[Here Maps], but you can use other kind of
tiling server compatible with https://www.openstreetmap.org/[Open Street
Maps].
7.  Setup an *analytics* server. For better compliance with Decidim
Social Contract, we recommend using https://matomo.org/[Matomo].
8.  Setup *backup* on your server. The most important things to save are
the `public/uploads` and the database.
9.  Decide and implement which kind of
*link:customization/authorizations.md[Authorization]* you're going to
use.
10. Comply with our License (Affero GPL 3) and *publish your code* to
http://github.com[GitHub] or wherever you want.
11. Review your *decidim initializer* on your application
(config/initializers/decidim.rb).
12. Configure your link:services/activejob.md[*ActiveJob*] background
queue.
13. If you want, configure your
link:services/social_providers.md[*social providers*] to enable login
using external applications.
14. Check that you don't have any *default users, emails and passwords*,
neither on the admin or on the system panel.

[[contents]]
Contents
~~~~~~~~

1.  Ideally you'll have a *Team* formed with experts on IT,
Communication, Participation, Design and Law.
2.  Texts for at least, *terms of use, privacy policy and frequently
asked questions*. To show the "Terms and conditions" body text in the
"Sign Up Form", it is a requirement that the slug of this page to be
equal `terms-and-conditions`.
3.  Comply with your current *legal requirements*, like to registrate
your privacy policy with the autorities (eg LOPD on Spain).
4.  Fill the *Participatory Processes Configuration Form* to prepare
your Participatory Process for Decidim.
5.  Read the *https://decidim.org/docs/[Administration manual]*.
6.  Participate on *http://meta.decidim.barcelona[MetaDecidim]*.
7.  Read the Decidim *https://decidim.org/contract/[Social Contract]*.
