The participatory democracy framework.

________________________________________________________________________________________________________________
Free Open-Source participatory democracy, citizen participation and open
government for cities and organizations
________________________________________________________________________________________________________________

https://decidim.org[Decidim] is a participatory democracy framework,
written in Ruby on Rails, originally developed for the Barcelona City
government online and offline participation website. Installing these
libraries will provide you a generator and gems to help you develop web
applications like the ones found on link:#example-applications[example
applications] or like http://staging.decidim.codegram.com[our demo
application].

All members of the Decidim community agree with
http://www.decidim.org/contract/[Decidim Social Contract or Code of
Democratic Guarantees].

'''''

https://rubygems.org/gems/decidim[image:https://img.shields.io/gem/v/decidim.svg[Gem]]
https://rubygems.org/gems/decidim[image:https://img.shields.io/gem/dt/decidim.svg[Gem]]
https://github.com/decidim/decidim/graphs/contributors[image:https://img.shields.io/github/contributors/decidim/decidim.svg[GitHub
contributors]]
http://rubydoc.info/github/decidim/decidim/master[image:http://img.shields.io/badge/yard-docs-blue.svg[Yard
Docs]]
https://gitter.im/decidim/decidim[image:https://img.shields.io/gitter/room/nwjs/nw.js.svg[Gitter]]

Code quality

https://circleci.com/gh/decidim/decidim[image:https://img.shields.io/circleci/project/github/decidim/decidim/master.svg[Build
Status]]
https://codeclimate.com/github/decidim/decidim/maintainability[image:https://api.codeclimate.com/v1/badges/ad8fa445086e491486b6/maintainability[Maintainability]]
https://crowdin.com/project/decidim[image:https://d322cqt584bo4o.cloudfront.net/decidim/localized.svg[Crowdin]]
http://inch-ci.org/github/decidim/decidim[image:http://inch-ci.org/github/decidim/decidim.svg?branch=master[Inline
docs]]
https://rocketvalidator.com/badges/link?url=http://staging.decidim.codegram.com/&report=a11y[image:https://rocketvalidator.com/badges/a11y_issues.svg?url=http://staging.decidim.codegram.com/[Accessibility
issues]]
https://rocketvalidator.com/badges/link?url=http://staging.decidim.codegram.com/&report=html[image:https://rocketvalidator.com/badges/html_issues.svg?url=http://staging.decidim.codegram.com/[HTML
issues]]

Project management https://waffle.io/decidim/decidim[[See on Waffle.io]]

https://github.com/decidim/decidim/issues?q=is%3Aopen+is%3Aissue+label%3Adiscussion[image:https://img.shields.io/waffle/label/decidim/decidim/discussion.svg[Stories
in Discussion]]
https://github.com/decidim/decidim/issues?q=is%3Aopen+is%3Aissue+label%3Aplanned[image:https://img.shields.io/waffle/label/decidim/decidim/planned.svg[Stories
in Planned]]
https://github.com/decidim/decidim/issues?q=is%3Aopen+is%3Aissue+label%3Abug[image:https://img.shields.io/waffle/label/decidim/decidim/bug.svg[Bugs]]
https://github.com/decidim/decidim/issues?q=is%3Aopen+is%3Aissue+label%3Ain-progress[image:https://img.shields.io/waffle/label/decidim/decidim/in-progress.svg[In
Progress]]
https://github.com/decidim/decidim/issues?q=is%3Aopen+is%3Aissue+label%3Ain-review[image:https://img.shields.io/waffle/label/decidim/decidim/in-review.svg[In
Review]]

'''''

[[what-do-you-need-to-do]]
What do you need to do?
-----------------------

* link:#getting-started-with-decidim[Get started with Decidim]
* link:#how-to-contribute[Contribute to the project]
* link:#modules[Modules]
* link:#browse-decidim[Create & browse development app]

'''''

[[getting-started-with-decidim]]
Getting started with Decidim
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TLDR: install gem, generate a Ruby on Rails app, enjoy.

[source,console]
----
gem install decidim
decidim decidim_application
----

We've set up a guide on how to install, set up and upgrade Decidim. See
the
https://github.com/decidim/decidim/blob/master/docs/getting_started.md[Getting
started guide].

[[how-to-contribute]]
How to contribute
~~~~~~~~~~~~~~~~~

See link:CONTRIBUTING.md[Contributing].

[[browse-decidim]]
Browse Decidim
^^^^^^^^^^^^^^

After you create a development app (`bundle exec rake development_app`),
you have to switch to it and boot the rails server with
`cd development_app && bundle exec rails s`.

After that, you can:

* Browse the main interface at `http://localhost:3000`, and log in as:
user@example.org | decidim123456
* Browse the admin interface at `http://localhost:3000/admin`, and log
in as: admin@example.org | decidim123456
* Browse the system interface at `http://localhost:3000/system`, and log
in as: system@example.org | decidim123456

Also, if you want to verify yourself against the default authorization
handler use a document number ended with "X".

[[modules]]
Modules
~~~~~~~

[[official-stable]]
Official (stable)
^^^^^^^^^^^^^^^^^

[width="100%",cols="41%,59%",options="header",]
|=======================================================================
|Module |Description
|https://github.com/decidim/decidim/tree/master/decidim-accountability[Accountability]
|Adds an accountability section to any participatory space so users can
follow along the state of the accepted proposals.

|https://github.com/decidim/decidim/tree/master/decidim-admin[Admin]
|Adds an administration dashboard so users can manage their organization
and all other entities.

|https://github.com/decidim/decidim/tree/master/decidim-api[API]
|Exposes a GraphQL API to programatically interact with the Decidim
platform via HTTP.

|https://github.com/decidim/decidim/tree/master/decidim-assemblies[Assemblies]
|Permanent participatory spaces.

|https://github.com/decidim/decidim/tree/master/decidim-budgets[Budgets]
|Adds a participatory budgets system to any participatory space.

|https://github.com/decidim/decidim/tree/master/decidim-comments[Comments]
|The Comments module adds the ability to include comments to any
resource which can be commentable by users.

|https://github.com/decidim/decidim/tree/master/decidim-conferences[Conferences]
|This module will be a configurator and generator of Conference pages,
understood as a collection of Meetings, with program, inscriptions and
categories

|https://github.com/decidim/decidim/tree/master/decidim-core[Core] |The
basics of Decidim: users, organizations, etc. This is the only required
engine to run Decidim, all the others are optional.

|https://github.com/decidim/decidim/tree/master/decidim-generators[Generators]
|It helps you with generating decidim applications & new components. It
provides the `decidim` executable.

|https://github.com/decidim/decidim/tree/master/decidim-participatory_processes[Participatory
Processes] |The main concept of a Decidim installation: participatory
processes.

|https://github.com/decidim/decidim/tree/master/decidim-dev[Dev] |Aids
the local development of Decidim's components.

|https://github.com/decidim/decidim/tree/master/decidim-meetings[Meeting]
|The Meeting module adds meeting to any participatory space. It adds a
CRUD engine to the admin and public view scoped inside the participatory
space.

|https://github.com/decidim/decidim/tree/master/decidim-pages[Pages]
|The Pages module adds static page capabilities to any participatory
space. It basically provides an interface to include arbitrary HTML
content to any step.

|https://github.com/decidim/decidim/tree/master/decidim-proposals[Proposals]
|The Proposals module adds one of the main components of Decidim: allows
users to contribute to a participatory space by creating proposals.

|https://github.com/decidim/decidim/tree/master/decidim-surveys[Surveys]
|Adds the ability for admins to create arbitrary surveys.

|https://github.com/decidim/decidim/tree/master/decidim-system[System]
|Multitenant Admin to manage multiple organizations in a single
installation.

|https://github.com/decidim/decidim/tree/master/decidim-sortitions[Sortitions]
|This component makes possible to select randomly a number of proposals
among a set of proposals (or a category of proposals within a set)
maximizing guarantees of randomness and avoiding manipulation of results
by the administrator.

|https://github.com/decidim/decidim/tree/master/decidim-consultations[Consultations]
|This module creates a new space for decidim to host consultations:
debates around critical questions and a proxy for eVoting

|https://github.com/decidim/decidim/tree/master/decidim-initiatives[Initiatives]
|Initiatives is the place on Decidim's where citizens can promote a
civic initiative. Unlike participatory processes that must be created by
an administrator, Civic initiatives can be created by any user of the
platform.

|https://github.com/decidim/decidim/tree/master/decidim-blogs[Blogs]
|This component makes possible to add posts ordered by publication time
to spaces.
|=======================================================================

[[community]]
Community
^^^^^^^^^

[width="100%",cols="41%,59%",options="header",]
|=======================================================================
|Module |Description
|https://github.com/diputacioBCN/decidim-diba/tree/master/decidim-census[Census]
|Allows to upload a census CSV file to perform authorizations against
real users parameterised by their age.

|https://github.com/podemos-info/decidim-module-crowdfundings[Crowdfunding]
|This rails engine implements a Decidim component that allows to the
administrators to configure crowfunding campaigns for a participatory
space.

|https://github.com/AjuntamentdeBarcelona/decidim-barcelona/tree/master/decidim-dataviz[DataViz]
|The Dataviz module adds the PAM data visualizations to any
participatory process but it is intended to be used just for the PAM
participatory process.

|https://github.com/ElectricThings/decidim-members[Members] |Members
list and search plugin for Decidim

|https://github.com/OpenSourcePolitics/decidim-polis[Pol.is] |Pol.is
integration on Decidim

|https://github.com/OpenSourcePolitics/decidim-user-export[User Export]
|Allow user export

|https://github.com/diputacioBCN/decidim-diba/tree/master/decidim-diba_census_api[Verification
DIBA Census API] |A decidim package to provice user authorizations
agains the Diputació of Barcelona census API

|https://github.com/podemos-info/decidim-module-census_connector[Verification
Podemos Census API] |A decidim package to provice user authorizations
against the Podemos census API

|https://github.com/podemos-info/decidim-module-votings[Votings] |An
administrator can add one or more votings to a participatory process or
assambly
|=======================================================================

[[following-our-license]]
Following our license
~~~~~~~~~~~~~~~~~~~~~

If you plan to release your application you'll need to publish it using
the same license: GPL Affero 3. We recommend doing that on GitHub before
publishing, you can read more on
"http://producingoss.com/en/governments-and-open-source.html#starting-open-for-govs[Being
Open Source From Day One is Especially Important for Government
Projects]". If you have any trouble you can contact us on
https://gitter.im/decidim/decidim[Gitter].

[[example-applications]]
Example applications
~~~~~~~~~~~~~~~~~~~~

Since Decidim is a ruby gem, you can check out the
https://github.com/decidim/decidim/network/dependents?type=application[dependent
repositories] to see how many applications are on the wild or tests that
other developers have made. Here's a partial list with some of the
projects that have used Decidim:

* http://staging.decidim.codegram.com[Demo]
* https://decidim.barcelona[Decidim Barcelona] -
https://github.com/AjuntamentdeBarcelona/decidim-barcelona[View code]
* https://www.lhon-participa.cat[L'H ON Participa] -
https://github.com/HospitaletDeLlobregat/decidim-hospitalet[View code]
* https://participa.terrassa.cat[Decidim Terrassa] -
https://github.com/AjuntamentDeTerrassa/decidim-terrassa[View code]
* https://decidim.sabadell.cat[Decidim Sabadell] -
https://github.com/AjuntamentDeSabadell/decidim-sabadell[View code]
* https://participa.gavaciutat.cat[Decidim Gavà] -
https://github.com/AjuntamentDeGava/decidim-gava[View code]
* https://decidim.santcugat.cat/[Decidim Sant Cugat] -
https://github.com/AjuntamentdeSantCugat/decidim-sant_cugat[View code]
* http://participa.vilanova.cat[Vilanova Participa] -
https://github.com/vilanovailageltru/decidim-vilanova[View code]
* https://erabaki.pamplona.es[Erabaki Pamplona] -
https://github.com/ErabakiPamplona/erabaki[View code]
* https://www.decidimmataro.cat[Decidim Mataró] -
https://github.com/AjuntamentDeMataro/decidim-mataro[View code]
* https://cndp.opensourcepolitics.eu/[Commission Nationale du Débat
Public (France)]
* https://meta.decidim.barcelona/[MetaDecidim] -
https://github.com/decidim/metadecidim[View Code]
